name: Clone

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone another repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone -b Beta https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/Aoichaan0513/Flast